import axiosInstance from "@/lib/axiosInstance";
import type { ApiResponse } from "@/types/base/ApiResponse";
import type { CertificateRequest } from "@/types/certificate/CertificateRequest";
import type { CertificateResponse } from "@/types/certificate/CertificateResponse";
import type { VerifyResponse } from "@/types/certificate/VerifyResponse";

/**
 * Issue a new certificate for the current vendor (organization).
 */
export const issueCertificateApi = async (
  data: CertificateRequest,
  organizationId: number,
): Promise<ApiResponse<CertificateResponse>> => {
  const response = await axiosInstance.post<ApiResponse<CertificateResponse>>(
    `/api/certificates/${organizationId}`,
    data,
  );
  return response.data;
};

/**
 * Verify a certificate by uploading the file generated by the system.
 */
export const verifyCertificateByFileApi = async (
  file: File,
): Promise<ApiResponse<VerifyResponse>> => {
  const formData = new FormData();
  formData.append("file", file);

  const response = await axiosInstance.post<ApiResponse<VerifyResponse>>(
    "/api/certificates/verify/by-file",
    formData,
    {
      headers: {
        "Content-Type": "multipart/form-data",
      },
    },
  );

  return response.data;
};

/**
 * Verify a certificate using its ID string.
 */
export const verifyCertificateApi = async (
  certificateId: string,
): Promise<ApiResponse<VerifyResponse>> => {
  const response = await axiosInstance.get<ApiResponse<VerifyResponse>>(
    `/api/certificates/${certificateId}/verify`,
  );
  return response.data;
};

/**
 * Download raw PDF bytes for a certificate.
 */
export const downloadCertificatePdfApi = async (
  certificateId: string,
): Promise<Blob> => {
  const response = await axiosInstance.get(
    `/api/certificates/${certificateId}/download`,
    {
      responseType: "blob",
    },
  );
  return response.data;
};

/**
 * Retrieve certificates issued by a specific organization.
 */
export const getCertificatesByOrganizationApi = async (
  organizationId: number,
): Promise<ApiResponse<CertificateResponse[]>> => {
  const response = await axiosInstance.get<ApiResponse<CertificateResponse[]>>(
    `/api/certificates/organization/${organizationId}`,
  );
  return response.data;
};

/**
 * Get certificate details by ID.
 */
export const getCertificateByIdApi = async (
  certificateId: string,
): Promise<ApiResponse<CertificateResponse>> => {
  const response = await axiosInstance.get<ApiResponse<CertificateResponse>>(
    `/api/certificates/${certificateId}`,
  );
  return response.data;
};

/**
 * Revoke an existing certificate.
 */
export const revokeCertificateApi = async (
  certificateId: string,
): Promise<ApiResponse<CertificateResponse>> => {
  const response = await axiosInstance.delete<ApiResponse<CertificateResponse>>(
    `/api/certificates/${certificateId}`,
  );
  return response.data;
};

/**
 * Reactivate a revoked certificate.
 */
export const reactivateCertificateApi = async (
  certificateId: string,
): Promise<ApiResponse<CertificateResponse>> => {
  const response = await axiosInstance.post<ApiResponse<CertificateResponse>>(
    `/api/certificates/${certificateId}/reactivate`,
  );
  return response.data;
};
