import axiosInstance from "@/lib/axiosInstance";
import type { AxiosError } from "axios";
import type { ApiResponse } from "@/types/base/ApiResponse";
import type { CertificateRequest } from "@/types/certificate/CertificateRequest";
import type { CertificateResponse } from "@/types/certificate/CertificateResponse";
import type { VerifyResponse } from "@/types/certificate/VerifyResponse";

/**
 * Issue a new certificate for the current vendor (organization).
 */
export const issueCertificateApi = async (
  data: CertificateRequest,
  organizationId: number,
): Promise<ApiResponse<CertificateResponse>> => {
  const response = await axiosInstance.post<ApiResponse<CertificateResponse>>(
    `/api/certificates/${organizationId}`,
    data,
  );
  return response.data;
};

/**
 * Verify a certificate by uploading the file generated by the system.
 */
export const verifyCertificateByFileApi = async (
  file: File,
): Promise<ApiResponse<VerifyResponse>> => {
  const formData = new FormData();
  formData.append("pdfFile", file);

  const response = await axiosInstance.post<ApiResponse<VerifyResponse>>(
    "/api/certificates/verify/file",
    formData,
    {
      headers: {
        "Content-Type": "multipart/form-data",
      },
    },
  );

  return response.data;
};

/**
 * Verify a certificate using its ID string.
 */
export const verifyCertificateApi = async (
  certificateId: string,
): Promise<ApiResponse<VerifyResponse>> => {
  const response = await axiosInstance.get<ApiResponse<VerifyResponse>>(
    `/api/certificates/${certificateId}/verify`,
  );
  return response.data;
};

/**
 * Download raw PDF bytes for a certificate.
 */
export const downloadCertificatePdfApi = async (
  certificateId: string,
): Promise<Blob> => {
  const response = await axiosInstance.get(
    `/api/certificates/${certificateId}/download`,
    {
      responseType: "blob",
    },
  );
  return response.data;
};

/**
 * Download certificate file and return blob plus filename (from Content-Disposition header).
 */
export const downloadCertificateApi = async (
  certificateId: string,
): Promise<{ filename: string; blob: Blob }> => {
  const response = await axiosInstance.get(
    `/api/certificates/${certificateId}/download`,
    {
      responseType: "blob",
    },
  );
  let filename = `${certificateId}.pdf`;
  const disposition = response.headers["content-disposition"] as
    | string
    | undefined;
  if (disposition) {
    const match = disposition.match(/filename="?([^";]+)"?/);
    if (match && match[1]) {
      filename = match[1];
    }
  }
  return { filename, blob: response.data };
};

/**
 * Retrieve certificates issued by a specific organization.
 */
export const getCertificatesByOrganizationApi = async (
  organizationId: number,
): Promise<ApiResponse<CertificateResponse[]>> => {
  const response = await axiosInstance.get<ApiResponse<CertificateResponse[]>>(
    `/api/certificates/organization/${organizationId}`,
  );
  return response.data;
};

/**
 * Get certificate details by ID.
 */
export const getCertificateByIdApi = async (
  certificateId: string,
): Promise<ApiResponse<CertificateResponse>> => {
  const response = await axiosInstance.get<ApiResponse<CertificateResponse>>(
    `/api/certificates/${certificateId}`,
  );
  return response.data;
};

/**
 * Revoke an existing certificate.
 */
export const revokeCertificateApi = async (
  certificateId: string,
): Promise<ApiResponse<CertificateResponse>> => {
  const response = await axiosInstance.delete<ApiResponse<CertificateResponse>>(
    `/api/certificates/${certificateId}/revoke`,
  );
  return response.data;
};

/**
 * Reactivate a revoked certificate.
 */
export const reactivateCertificateApi = async (
  certificateId: string,
): Promise<ApiResponse<CertificateResponse>> => {
  const response = await axiosInstance.post<ApiResponse<CertificateResponse>>(
    `/api/certificates/${certificateId}/reissue`,
  );
  return response.data;
};

/**
 * Claim a certificate by its unique code. The backend figures out student from token.
 */
export const claimCertificateApi = async (
  claimCode: string,
): Promise<ApiResponse<CertificateResponse>> => {
  const encodedCode = encodeURIComponent(claimCode);
  const claimEndpoints = [
    `/api/certificates/claim/${encodedCode}`,
    `/api/certificates/${encodedCode}/claim`,
  ];

  let lastError: unknown = null;

  for (const endpoint of claimEndpoints) {
    try {
      const response =
        await axiosInstance.post<ApiResponse<CertificateResponse>>(endpoint);
      return response.data;
    } catch (error) {
      lastError = error;
      const status = (error as AxiosError).response?.status;

      // If endpoint doesn't exist, try the fallback path.
      if (status === 404) {
        continue;
      }

      throw error;
    }
  }

  throw lastError;
};

/**
 * Fetch certificates belonging to the currently authenticated student.
 */
export const getMyCertificatesApi = async (): Promise<
  ApiResponse<CertificateResponse[]>
> => {
  const response = await axiosInstance.get<ApiResponse<CertificateResponse[]>>(
    "/api/certificates/my-certificates",
  );
  return response.data;
};

export interface OcrCertificateResponse {
  certificateId?: string;
  studentName?: string;
  dateofBirth?: string;
  major?: string;
  graduationYear?: number;
  gpa?: number;
  certificateType?: string;
  issueDate?: string;
}

/**
 * Extract certificate information from uploaded image (OCR).
 */
export const extractCertificateFromImageApi = async (
  file: File,
): Promise<ApiResponse<OcrCertificateResponse>> => {
  const formData = new FormData();
  formData.append("file", file);

  const response = await axiosInstance.post<
    ApiResponse<OcrCertificateResponse>
  >("/api/certificates/upload", formData);

  return response.data;
};
